name: Compile and Test

on:
  pull_request:
    branches: ["master"]
  workflow_call:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: Nigui/localx/.github/actions/setup@master
      - name: Compile
        run: deno task build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Nigui/localx/.github/actions/setup@master
      - name: Run tests
        run: deno task test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: Nigui/localx/.github/actions/setup@master
      - name: Run linter
        run: deno task lint:check

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: Nigui/localx/.github/actions/setup@master
      - name: Run formatter
        run: deno task format:check
